#cloud-config
ssh_pwauth: true
groups:
  - ${admin_username}
users:
  - default
  - name: ${admin_username}
    primary_group: ${admin_username}
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_key}
package_upgrade: true
packages:
  - jq
runcmd:
  - curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - apt-get update && apt-get install azure-cli
  - az aks install-cli
  - curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  - apt-get install apt-transport-https --yes
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - apt-get update && apt-get install helm
  - chown -R ${admin_username}:${admin_username} /home/${admin_username}